name: Push file to another repository
description: >-
  Useful to push a file to another repository to be used, for example, via github
  pages
inputs:
  source-filepath:
    description: Source directory from the origin directory
    required: true
  destination-github-username:
    description: Name of the destination username/organization
    required: true
  destination-repository-name:
    description: Destination repository
    required: true
  user-email:
    description: Email for the git commit
    required: true
  github-server:
    description: 'Github server'
    default: 'github.com'
    required: false
  user-name:
    description: >-
      [Optional] Name for the git commit. Defaults to the destination
      username/organization name
    required: false
    default: ''
  destination-repository-username:
    description: '[Optional] Username/organization for the destination repository'
    required: false
    default: ''
  target-branch:
    description: >-
      [Optional] set target branch name for the destination repository. Defaults
      to "main"
    default: main
    required: false
  commit-message:
    description: >-
      [Optional] commit message for the output repository. ORIGIN_COMMIT is
      replaced by the URL@commit in the origin repo
    default: Update from ORIGIN_COMMIT
    required: false
  target-directory:
    description: '[Optional] The directory copy the file to'
    default: ''
    required: false
  target-filename:
    description: File Name to give the file when copied into the destination repo
    required: true
  create-target-branch-if-needed:
    type: boolean
    description: >-
      [Optional] create target branch if not exist. Defaults to `false`
    default: false
    required: false
  img-folder:
    description: "Additional folder to copy to the target folder"
    required: false
    default: "IGNORE"

runs:
  using: docker
  image: Dockerfile
  args:
    - '${{ inputs.source-filepath }}'
    - '${{ inputs.destination-github-username }}'
    - '${{ inputs.destination-repository-name }}'
    - '${{ inputs.github-server }}'
    - '${{ inputs.user-email }}'
    - '${{ inputs.user-name }}'
    - '${{ inputs.destination-repository-username }}'
    - '${{ inputs.target-branch }}'
    - '${{ inputs.commit-message }}'
    - '${{ inputs.target-directory }}'
    - '${{ inputs.target-filename }}'
    - '${{ inputs.create-target-branch-if-needed }}'
    - '${{ inputs.img-folder }}'
branding:
  icon: git-commit
  color: green
